version: '3.8'

services:
  web:
    image: django:latest
    container_name: django_web
    volumes:
      - .:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1


